[package]
name = "brush-character"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
glam.workspace = true
gltf = { version = "1.4", default-features = false, features = ["import", "utils", "names"] }
log.workspace = true
wgpu = { workspace = true, features = ["wgsl"] }

[lints]
workspace = true
